/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'ownedCars' : Array<bigint>,
  'selectedCar' : [] | [bigint],
  'displayName' : string,
  'diamonds' : bigint,
  'racesWon' : bigint,
  'gold' : bigint,
  'racesParticipated' : bigint,
  'level' : bigint,
  'score' : bigint,
  'missionsCompleted' : bigint,
}
export interface _SERVICE {
  'createProfile' : ActorMethod<[string], undefined>,
  'getAllLuxuryCars' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'unlockWithGold' : bigint,
        'name' : string,
        'speed' : bigint,
        'acceleration' : bigint,
        'rarity' : string,
        'handling' : bigint,
        'unlockWithDiamonds' : bigint,
      }
    >
  >,
  'getLeaderboard' : ActorMethod<[], Array<[string, bigint]>>,
  'getPlayerProfile' : ActorMethod<[Principal], Profile>,
  'purchaseLuxuryCar' : ActorMethod<[bigint], undefined>,
  'selectLuxuryCar' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];