/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Profile = IDL.Record({
  'ownedCars' : IDL.Vec(IDL.Nat),
  'selectedCar' : IDL.Opt(IDL.Nat),
  'displayName' : IDL.Text,
  'diamonds' : IDL.Nat,
  'racesWon' : IDL.Nat,
  'gold' : IDL.Nat,
  'racesParticipated' : IDL.Nat,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'missionsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createProfile' : IDL.Func([IDL.Text], [], []),
  'getAllLuxuryCars' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'unlockWithGold' : IDL.Nat,
            'name' : IDL.Text,
            'speed' : IDL.Nat,
            'acceleration' : IDL.Nat,
            'rarity' : IDL.Text,
            'handling' : IDL.Nat,
            'unlockWithDiamonds' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPlayerProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'purchaseLuxuryCar' : IDL.Func([IDL.Nat], [], []),
  'selectLuxuryCar' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Profile = IDL.Record({
    'ownedCars' : IDL.Vec(IDL.Nat),
    'selectedCar' : IDL.Opt(IDL.Nat),
    'displayName' : IDL.Text,
    'diamonds' : IDL.Nat,
    'racesWon' : IDL.Nat,
    'gold' : IDL.Nat,
    'racesParticipated' : IDL.Nat,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'missionsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    'createProfile' : IDL.Func([IDL.Text], [], []),
    'getAllLuxuryCars' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'unlockWithGold' : IDL.Nat,
              'name' : IDL.Text,
              'speed' : IDL.Nat,
              'acceleration' : IDL.Nat,
              'rarity' : IDL.Text,
              'handling' : IDL.Nat,
              'unlockWithDiamonds' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPlayerProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'purchaseLuxuryCar' : IDL.Func([IDL.Nat], [], []),
    'selectLuxuryCar' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };